[plat]
# The base address of the user space.
user-space-base = 0         # uint
# The base address for user interpreter.
user-interp-base = 0   # uint
# The size of the user space.
user-space-size = 0         # uint

# The highest address of the user stack.
user-stack-top = 0          # uint
# The size of the user stack.
user-stack-size = 0         # uint
# The lowest address of the user heap.
user-heap-base = 0        # uint
# The size of the user heap.
user-heap-size = 0          # uint

# The size of the kernel stack.
kernel-stack-size = 0       # uint
